### ISSUE TITLE
Ox panic

### ISSUE THREAD

**Issue by mjf** [curlpipe/ox#84]
**Describe the bug**
*Ox* panic!

**To Reproduce**
1. `ox`
2. `C-backspace` `C-backspace` (normal `backspace` does not work either on *XTerm*)

**Expected behavior**
*Ox* doesn't panic.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: *GNU/Linux*, *X.org*, *XTerm*

**Backtrace**
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/document.rs:385:21
stack backtrace:
   0:     0x7f65570e6f86 - backtrace::backtrace::libunwind::trace::hc5f524da7fd1bf36
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7f65570e6f86 - backtrace::backtrace::trace_unsynchronized::hd11faf0c738b3334
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7f65570e6f86 - std::sys_common::backtrace::_print_fmt::h178f112e0f8e4683
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7f65570e6f86 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb0a22bd860f1c150
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f655706e81c - core::fmt::write::haef1c8ec4be874ff
                               at src/libcore/fmt/mod.rs:1076
   5:     0x7f65570e6516 - std::io::Write::write_fmt::h076fbfae51d9d5ec
                               at src/libstd/io/mod.rs:1537
   6:     0x7f65570e5f1a - std::sys_common::backtrace::_print::he39ed648b9862ab3
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f65570e5f1a - std::sys_common::backtrace::print::h160b78e9d6f039e6
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f65570e5f1a - std::panicking::default_hook::{{closure}}::h585caa318b2cae3c
                               at src/libstd/panicking.rs:198
   9:     0x7f65570e56a8 - std::panicking::default_hook::h41b5eb8bbd1a0d2c
                               at src/libstd/panicking.rs:218
  10:     0x7f65570e56a8 - std::panicking::rust_panic_with_hook::h8dd35d3cd11497d7
                               at src/libstd/panicking.rs:486
  11:     0x7f65570e533a - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x7f655706c0f0 - core::panicking::panic_fmt::hdf118db3fcd2d481
                               at src/libcore/panicking.rs:101
  13:     0x7f655706bf81 - core::panicking::panic_bounds_check::h8bd88781b8fd4e25
                               at src/libcore/panicking.rs:73
  14:     0x7f6556ffc2e0 - ox::editor::Editor::execute::h32f55e56078f9465
  15:     0x7f655700d8d4 - ox::main::hb78e91452648bbca
  16:     0x7f65570efe73 - std::rt::lang_start_internal::{{closure}}::{{closure}}::h9bf2a999c48d74ab
                               at src/libstd/rt.rs:52
  17:     0x7f65570efe73 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd248e743eb45f457
                               at src/libstd/sys_common/backtrace.rs:130
  18:     0x7f655701726d - main
  19:     0x7f65561a7a05 - __libc_start_main
  20:     0x7f6556fcc919 - <unknown>
  21:                0x0 - <unknown>
```

**Comment by curlpipe** [comment]
Already fixed in 0.2.7 which will be released soon.
