### ISSUE TITLE
twice Backspace on pos 1,1 breakdown ox editor

### ISSUE THREAD

**Issue by cavo-github** [curlpipe/ox#85]
**Describe the bug**
When press backspace twice on start of document, editor breakdown.

**To Reproduce**
1. run editor
2. press backspace twice
3. See error

**Expected behavior**
Nothing.

**Screenshots**
`RUST_BACKTRACE=full ./target/debug/ox`
Formated for easy read:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/document.rs:385:21
  stack backtrace:
    0:     0x557de3cda354 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc0e9847006ce73d8
    1:     0x557de3cfb26d - core::fmt::write::h529bfd0f467cbcc1
    2:     0x557de3cce087 - std::io::Write::write_fmt::he0f42c423f67a7e8
    3:     0x557de3cd2090 - std::panicking::default_hook::{{closure}}::h5a211c653c9c36b7
    4:     0x557de3cd1d7e - std::panicking::default_hook::h4a5d23e1d3be3b07
    5:     0x557de3cd26b4 - std::panicking::rust_panic_with_hook::hac1a14dab8c19a8f
    6:     0x557de3cd229b - rust_begin_unwind
    7:     0x557de3cfa1b1 - core::panicking::panic_fmt::h7f0bd80c7f2740a6
    8:     0x557de3cfa172 - core::panicking::panic_bounds_check::h4bfce8dc789ad82a
    9:     0x557de38adb35 - <usize as core::slice::SliceIndex<[T]>>::index::hb854703e103d82df
                              at /rustc/1.46.0/src/libcore/slice/mod.rs:3103
    10:     0x557de395c282 - core::slice::<impl core::ops::index::Index<I> for [T]>::index::hc89505d804332244
                               at /rustc/1.46.0/src/libcore/slice/mod.rs:2955
    11:     0x557de391122d - <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index::hdc35991c8142e583
                               at /rustc/1.46.0/src/liballoc/vec.rs:1975
    12:     0x557de3934680 - ox::document::Document::splice_up::heb60d0d2371169f2
                               at src/document.rs:385
    13:     0x557de3935aee - ox::document::Document::execute::h05e3d7c1fdada812
                               at src/document.rs:496
    14:     0x557de38b6e5f - ox::editor::Editor::execute::hd31d8aaf98352ca0
                               at src/editor.rs:437
    15:     0x557de38b3964 - ox::editor::Editor::process_input::h8f445c90c0cb8f90
                               at src/editor.rs:180
    16:     0x557de38b2c3a - ox::editor::Editor::run::h0080e19bf938fbf8
                               at src/editor.rs:100
    17:     0x557de391d944 - ox::main::{{closure}}::h6132fa7dc3360fe2
                               at src/main.rs:71
    18:     0x557de38ac4fc - std::panicking::try::do_call::hc0bb5ffafd8b4559
                               at /rustc/1.46.0/src/libstd/panicking.rs:348
    19:     0x557de38ac5bd - __rust_try
    20:     0x557de38ac474 - std::panicking::try::hd8969b5357998d73
                               at /rustc/1.46.0/src/libstd/panicking.rs:325
    21:     0x557de38e3ca9 - std::panic::catch_unwind::h6c0d734ea97e739c
                               at /rustc/1.46.0/src/libstd/panic.rs:394
    22:     0x557de395b9f9 - ox::main::h0b8e7c0625fdec9c
                               at src/main.rs:48
    23:     0x557de393823b - std::rt::lang_start::{{closure}}::hd2ee05b2918ffe1c
                               at /rustc/1.46.0/src/libstd/rt.rs:67
    24:     0x557de3ccf657 - std::rt::lang_start_internal::h58b83ee8aef7ae36
    25:     0x557de3938217 - std::rt::lang_start::h7da91c725a72fa39
                               at /rustc/1.46.0/src/libstd/rt.rs:67
    26:     0x557de395be5a - main
    27:     0x7f4740a2bedb - __libc_start_main
    28:     0x557de38a81ba - _start
    29:                0x0 - <unknown>
```

**Desktop (please complete the following information):**
 - OS: GNU/Linux (Gentoo)
 - Rust: 1.46.0
 - ox: 0.2.6 (from git)

**Comment by curlpipe** [comment]
Already fixed in 0.2.7 which will be released soon.
